import { apiConfig } from "@/lib/api-config";
import type {
  ProfileContext,
  DiscoveryPhase,
  PersonalityDimension,
  GeneratedQuestion,
  QuestionGenerationInput,
} from "@/types/personality";
import type { PsychologyModality } from "@/types/quiz";
import { generateId } from "@/lib/utils";

/**
 * DiscoveryQuestionService
 *
 * Generates personalized daily questions for the 14-day discovery arc.
 * Each question serves double duty: deepening the couple's connection
 * AND revealing personality dimensions for the profile builder.
 *
 * Questions are generated by AI based on:
 * - The current discovery phase and day
 * - Which personality dimensions still need signal
 * - The user's demonstrated comfort level
 * - What questions have already been asked
 */
export class DiscoveryQuestionService {
  private static instance: DiscoveryQuestionService;

  private constructor() {}

  static getInstance(): DiscoveryQuestionService {
    if (!DiscoveryQuestionService.instance) {
      DiscoveryQuestionService.instance = new DiscoveryQuestionService();
    }
    return DiscoveryQuestionService.instance;
  }

  /**
   * Generate questions for a specific day in the discovery arc.
   */
  async generateDailyQuestions(input: QuestionGenerationInput): Promise<GeneratedQuestion[]> {
    const { openai } = apiConfig.apiKeys;

    if (!openai) {
      return this.getFallbackQuestions(input.discoveryPhase, input.timeSlot, input.count);
    }

    const systemPrompt = this.buildSystemPrompt();
    const userPrompt = this.buildGenerationPrompt(input);

    try {
      const response = await fetch(`${apiConfig.endpoints.openai}/chat/completions`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${openai}`,
        },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
          ],
          temperature: 0.8,
          max_tokens: 1500,
          response_format: { type: "json_object" },
        }),
      });

      if (!response.ok) {
        throw new Error(`Question generation failed: ${response.status}`);
      }

      const data = await response.json();
      const content = data.choices[0]?.message?.content;

      if (!content) {
        throw new Error("Empty response from question generation");
      }

      return this.parseGeneratedQuestions(content, input);
    } catch (error) {
      console.error("Question generation failed:", error);
      return this.getFallbackQuestions(input.discoveryPhase, input.timeSlot, input.count);
    }
  }

  private buildSystemPrompt(): string {
    return `You are a relationship psychologist crafting personalized daily questions for couples. Your questions serve two purposes:

1. **Connection**: Help the couple deepen their understanding of each other through meaningful conversation.
2. **Discovery**: Naturally reveal personality dimensions (attachment style, love language, conflict patterns, emotional expression, values, intimacy preferences, relational identity) without feeling like an assessment.

Rules for crafting questions:
- NEVER sound like a quiz, assessment, or clinical interview
- Questions should feel like something a wise, warm friend would ask over dinner
- Use the couple's names when provided to make it personal
- Match the intimacy level to the discovery phase — don't push vulnerability too fast
- Each question should be open-ended, inviting a narrative response (not yes/no)
- Reference the couple's specific context (relationship structure, what's been shared before)
- Vary between questions about self, partner, and the relationship as a whole
- Include a mix of reflective ("Think about..."), experiential ("Remember when..."), and forward-looking ("Imagine if...") prompts

Phase guide:
- **rhythm** (Days 1-3): Light, playful, warm. Focus: values, positive memories, dreams. Intimacy level 1-2.
- **deepening** (Days 4-6): Emotional depth. Focus: attachment patterns, emotional needs, what they cherish. Intimacy level 2-3.
- **navigating** (Days 7-9): How they handle challenge. Focus: conflict styles, love language confirmation, repair. Intimacy level 2-4.
- **layers** (Days 10-12): Vulnerability and intimacy. Focus: intimacy preferences, deeper emotional patterns, identity. Intimacy level 3-4.
- **mirror** (Days 13-14): Integration. Focus: celebrating what's been discovered, looking forward. Intimacy level 3-5.

Respond with JSON:
{
  "questions": [{
    "text": "the question text",
    "targetDimensions": ["dimension1", "dimension2"],
    "modality": "PsychologyModality",
    "category": "category name",
    "intimacyLevel": 1-5,
    "rationale": "why this question was chosen"
  }]
}`;
  }

  private buildGenerationPrompt(input: QuestionGenerationInput): string {
    const { profileContext, discoveryDay, discoveryPhase, targetDimensions, timeSlot, count } =
      input;

    const partnerRef = profileContext.partnerName
      ? `Their partner's name is ${profileContext.partnerName}.`
      : "Partner name not yet shared.";

    const structureRef = profileContext.relationshipStructure
      ? `Relationship structure: ${profileContext.relationshipStructure}.`
      : "";

    const sensitivitiesRef =
      profileContext.sensitivities.length > 0
        ? `Be gentle around: ${profileContext.sensitivities.join(", ")}.`
        : "";

    const modalitiesRef =
      profileContext.preferredModalities.length > 0
        ? `Modalities they respond well to: ${profileContext.preferredModalities.join(", ")}.`
        : "";

    return `Generate ${count} personalized question(s) for ${profileContext.userName}.

**Discovery Day**: ${discoveryDay} of 14
**Phase**: ${discoveryPhase}
**Time**: ${timeSlot === "AM" ? "Morning (warm, energizing tone)" : "Evening (reflective, intimate tone)"}
**Comfort level**: ${Math.round(profileContext.comfortLevel * 100)}% openness to vulnerability

${partnerRef} ${structureRef}

**What we know so far**: ${profileContext.knownTraits}
**Dimensions needing more signal**: ${targetDimensions.join(", ")}
${modalitiesRef}
${sensitivitiesRef}

Generate questions that feel like natural conversation starters while revealing signals about: ${targetDimensions.slice(0, 3).join(", ")}.`;
  }

  private parseGeneratedQuestions(
    raw: string,
    input: QuestionGenerationInput
  ): GeneratedQuestion[] {
    try {
      const parsed = JSON.parse(raw);

      return (parsed.questions || []).map(
        (q: {
          text: string;
          targetDimensions: string[];
          modality: string;
          category: string;
          intimacyLevel: number;
          rationale: string;
        }) => ({
          id: generateId(),
          text: q.text,
          targetDimensions: q.targetDimensions as PersonalityDimension[],
          modality: q.modality as PsychologyModality,
          category: q.category,
          intimacyLevel: Math.min(5, Math.max(1, q.intimacyLevel)) as 1 | 2 | 3 | 4 | 5,
          rationale: q.rationale,
        })
      );
    } catch (error) {
      console.error("Failed to parse generated questions:", error);
      return this.getFallbackQuestions(input.discoveryPhase, input.timeSlot, input.count);
    }
  }

  // ─── Phase-Specific Dimension Targeting ─────────────────────────────────

  /**
   * Determine which dimensions to prioritize for a given discovery phase.
   * This ensures the right signals are gathered at the right time.
   */
  static getDimensionPriority(
    phase: DiscoveryPhase,
    uncertainDimensions: PersonalityDimension[]
  ): PersonalityDimension[] {
    const phaseTargets: Record<DiscoveryPhase, PersonalityDimension[]> = {
      rhythm: ["values", "emotionalExpression", "relationalIdentity"],
      deepening: ["attachment", "emotionalExpression", "loveLanguage"],
      navigating: ["conflict", "loveLanguage", "attachment"],
      layers: ["intimacy", "emotionalExpression", "values"],
      mirror: ["relationalIdentity", "values", "attachment"],
    };

    const phasePriority = phaseTargets[phase];

    // Prioritize uncertain dimensions that align with the current phase
    const aligned = phasePriority.filter((d) => uncertainDimensions.includes(d));
    const remaining = uncertainDimensions.filter((d) => !aligned.includes(d));

    return [...aligned, ...remaining];
  }

  // ─── Fallback Questions ─────────────────────────────────────────────────

  private getFallbackQuestions(
    phase: DiscoveryPhase,
    timeSlot: "AM" | "PM",
    count: number
  ): GeneratedQuestion[] {
    const fallbacks: Record<DiscoveryPhase, GeneratedQuestion[]> = {
      rhythm: [
        {
          id: generateId(),
          text: "What's one thing that always makes you smile when you think about your relationship?",
          targetDimensions: ["values", "emotionalExpression"],
          modality: "Positive Psychology",
          category: "Appreciation & Gratitude",
          intimacyLevel: 1,
          rationale: "Warm opener — reveals what they value and emotional expressiveness",
        },
        {
          id: generateId(),
          text: "If you could relive one day together from scratch, which would it be and what made it special?",
          targetDimensions: ["values", "loveLanguage"],
          modality: "Narrative Therapy",
          category: "Shared Memories",
          intimacyLevel: 1,
          rationale: "Memory recall reveals values and love language through what they highlight",
        },
        {
          id: generateId(),
          text: "What's something you've been curious to try together but haven't brought up yet?",
          targetDimensions: ["intimacy", "emotionalExpression"],
          modality: "Positive Psychology",
          category: "Adventure & Fun",
          intimacyLevel: 2,
          rationale: "Reveals comfort with new experiences and emotional openness",
        },
      ],
      deepening: [
        {
          id: generateId(),
          text: "When you've had a really difficult day, what does support from your partner look like for you?",
          targetDimensions: ["attachment", "loveLanguage"],
          modality: "Attachment Theory",
          category: "Emotional Intimacy",
          intimacyLevel: 2,
          rationale: "Directly reveals attachment needs and love language preferences",
        },
        {
          id: generateId(),
          text: "What feeling do you find hardest to express to your partner, and what holds you back?",
          targetDimensions: ["emotionalExpression", "attachment"],
          modality: "Emotional Focused Therapy",
          category: "Emotional Intimacy",
          intimacyLevel: 3,
          rationale: "Maps emotional expression boundaries and attachment avoidance",
        },
        {
          id: generateId(),
          text: "Think about a moment when you felt truly understood by your partner. What happened?",
          targetDimensions: ["attachment", "loveLanguage"],
          modality: "Imago Therapy",
          category: "Emotional Intimacy",
          intimacyLevel: 2,
          rationale: "Reveals what 'seen and heard' means to them — attachment and LL signal",
        },
      ],
      navigating: [
        {
          id: generateId(),
          text: "When you and your partner disagree about something that matters, what's your first instinct?",
          targetDimensions: ["conflict", "attachment"],
          modality: "Gottman Method",
          category: "Communication & Conflict",
          intimacyLevel: 3,
          rationale: "Directly maps conflict pattern — pursue, withdraw, or validate",
        },
        {
          id: generateId(),
          text: "What's the kindest thing your partner does for you regularly — something they might not even realize matters?",
          targetDimensions: ["loveLanguage", "values"],
          modality: "Love Languages",
          category: "Love Languages & Affection",
          intimacyLevel: 2,
          rationale: "Confirms love language through what they notice and appreciate",
        },
        {
          id: generateId(),
          text: "After a disagreement, what helps you feel reconnected? What does repair look like between you two?",
          targetDimensions: ["conflict", "attachment"],
          modality: "Gottman Method",
          category: "Communication & Conflict",
          intimacyLevel: 3,
          rationale: "Maps repair capacity and attachment recovery patterns",
        },
      ],
      layers: [
        {
          id: generateId(),
          text: "What part of yourself do you protect most in your relationship — and what would it take to let that guard down?",
          targetDimensions: ["intimacy", "attachment"],
          modality: "Emotional Focused Therapy",
          category: "Emotional Intimacy",
          intimacyLevel: 4,
          rationale: "Maps vulnerability boundaries and attachment avoidance directly",
        },
        {
          id: generateId(),
          text: "How has your definition of intimacy changed since the beginning of your relationship?",
          targetDimensions: ["intimacy", "emotionalExpression"],
          modality: "Attachment Theory",
          category: "Intimacy & Physical",
          intimacyLevel: 3,
          rationale: "Reveals intimacy evolution and comfort with the topic itself",
        },
        {
          id: generateId(),
          text: "What's something your partner does that makes you feel most like yourself?",
          targetDimensions: ["relationalIdentity", "loveLanguage"],
          modality: "Imago Therapy",
          category: "Personal Growth",
          intimacyLevel: 3,
          rationale: "Reveals relational identity — who they are within the partnership",
        },
      ],
      mirror: [
        {
          id: generateId(),
          text: "Over the past two weeks, what's something new you've noticed about yourself or your relationship through these conversations?",
          targetDimensions: ["relationalIdentity", "values"],
          modality: "Narrative Therapy",
          category: "Personal Growth",
          intimacyLevel: 3,
          rationale: "Meta-reflection that reveals self-awareness and growth orientation",
        },
        {
          id: generateId(),
          text: "If your relationship had a superpower — something you do better together than anyone else — what would it be?",
          targetDimensions: ["values", "relationalIdentity"],
          modality: "Positive Psychology",
          category: "Appreciation & Gratitude",
          intimacyLevel: 2,
          rationale: "Celebrates the couple identity and reveals core relational values",
        },
        {
          id: generateId(),
          text: "What's one thing you want your partner to know you've been carrying — something these questions have helped you see more clearly?",
          targetDimensions: ["emotionalExpression", "attachment"],
          modality: "Emotional Focused Therapy",
          category: "Emotional Intimacy",
          intimacyLevel: 4,
          rationale: "Deep vulnerability prompt for the integration phase — capstone moment",
        },
      ],
    };

    const phaseQuestions = fallbacks[phase] || fallbacks.rhythm;

    // Filter by time slot tone preference (AM = lighter, PM = deeper)
    if (timeSlot === "AM") {
      phaseQuestions.sort((a, b) => a.intimacyLevel - b.intimacyLevel);
    } else {
      phaseQuestions.sort((a, b) => b.intimacyLevel - a.intimacyLevel);
    }

    return phaseQuestions.slice(0, count);
  }
}
