import { AIModelService } from "@/services/aiModelService";
import type {
  ProfileContext,
  DiscoveryPhase,
  PersonalityDimension,
  GeneratedQuestion,
  QuestionGenerationInput,
} from "@/types/personality";
import type { PsychologyModality } from "@/types/quiz";
import type { SessionQuestion, MCOption, QuestionFormat } from "@/types/session";
import { generateId } from "@/lib/utils";

/**
 * DiscoveryQuestionService
 *
 * Generates personalized daily questions for the 14-day discovery arc.
 * Each question serves double duty: deepening the couple's connection
 * AND revealing personality dimensions for the profile builder.
 *
 * Questions are generated by AI based on:
 * - The current discovery phase and day
 * - Which personality dimensions still need signal
 * - The user's demonstrated comfort level
 * - What questions have already been asked
 */
export class DiscoveryQuestionService {
  private static instance: DiscoveryQuestionService;

  private constructor() {}

  static getInstance(): DiscoveryQuestionService {
    if (!DiscoveryQuestionService.instance) {
      DiscoveryQuestionService.instance = new DiscoveryQuestionService();
    }
    return DiscoveryQuestionService.instance;
  }

  /**
   * Generate questions for a specific day in the discovery arc.
   */
  async generateDailyQuestions(input: QuestionGenerationInput): Promise<GeneratedQuestion[]> {
    const systemPrompt = this.buildSystemPrompt();
    const userPrompt = this.buildGenerationPrompt(input);

    try {
      const aiService = AIModelService.getInstance();
      const response = await aiService.complete({
        taskType: "question-generation",
        systemPrompt: systemPrompt,
        userPrompt: userPrompt,
        temperature: 0.8,
        maxTokens: 2000,
        jsonMode: true,
      });

      return this.parseGeneratedQuestions(response.content, input);
    } catch (error) {
      console.error("Question generation failed:", error);
      return this.getFallbackQuestions(input.discoveryPhase, input.timeSlot, input.count);
    }
  }

  private buildSystemPrompt(): string {
    return `You are a relationship psychologist crafting personalized daily questions for someone working on their relationship growth. Your questions serve two purposes:

1. **Connection**: Help the couple deepen their understanding of each other through meaningful conversation.
2. **Discovery**: Naturally reveal personality dimensions (attachment style, love language, conflict patterns, emotional expression, values, intimacy preferences, relational identity) without feeling like an assessment.

Rules for crafting questions:
- NEVER sound like a quiz, assessment, or clinical interview
- Questions should feel like something a wise, warm friend would ask over dinner
- Use the couple's names when provided to make it personal
- Match the intimacy level to the discovery phase — don't push vulnerability too fast
- Each question should be open-ended, inviting a narrative response (not yes/no)
- Reference the couple's specific context (relationship structure, what's been shared before)
- Vary between questions about self, partner, and the relationship as a whole
- Include a mix of reflective ("Think about..."), experiential ("Remember when..."), and forward-looking ("Imagine if...") prompts

Phase guide:
- **rhythm** (Days 1-3): Light, playful, warm. Focus: values, positive memories, dreams. Intimacy level 1-2.
- **deepening** (Days 4-6): Emotional depth. Focus: attachment patterns, emotional needs, what they cherish. Intimacy level 2-3.
- **navigating** (Days 7-9): How they handle challenge. Focus: conflict styles, love language confirmation, repair. Intimacy level 2-4.
- **layers** (Days 10-12): Vulnerability and intimacy. Focus: intimacy preferences, deeper emotional patterns, identity. Intimacy level 3-4.
- **mirror** (Days 13-14): Integration. Focus: celebrating what's been discovered, looking forward. Intimacy level 3-5.

Respond with JSON:
{
  "questions": [{
    "text": "the question text",
    "targetDimensions": ["dimension1", "dimension2"],
    "modality": "PsychologyModality",
    "category": "category name",
    "intimacyLevel": 1-5,
    "rationale": "why this question was chosen"
  }]
}`;
  }

  private buildGenerationPrompt(input: QuestionGenerationInput): string {
    const { profileContext, discoveryDay, discoveryPhase, targetDimensions, timeSlot, count } =
      input;

    const partnerRef = profileContext.partnerName
      ? `Their partner's name is ${profileContext.partnerName}.`
      : "Partner name not yet shared.";

    const structureRef = profileContext.relationshipStructure
      ? `Relationship structure: ${profileContext.relationshipStructure}.`
      : "";

    const sensitivitiesRef =
      profileContext.sensitivities.length > 0
        ? `Be gentle around: ${profileContext.sensitivities.join(", ")}.`
        : "";

    const modalitiesRef =
      profileContext.preferredModalities.length > 0
        ? `Modalities they respond well to: ${profileContext.preferredModalities.join(", ")}.`
        : "";

    return `Generate ${count} personalized question(s) for ${profileContext.userName}.

**Discovery Day**: ${discoveryDay} of 14
**Phase**: ${discoveryPhase}
**Time**: ${timeSlot === "AM" ? "Morning (warm, energizing tone)" : "Evening (reflective, intimate tone)"}
**Comfort level**: ${Math.round(profileContext.comfortLevel * 100)}% openness to vulnerability

${partnerRef} ${structureRef}

**What we know so far**: ${profileContext.knownTraits}
**Dimensions needing more signal**: ${targetDimensions.join(", ")}
${modalitiesRef}
${sensitivitiesRef}

Generate questions that feel like natural conversation starters while revealing signals about: ${targetDimensions.slice(0, 3).join(", ")}.`;
  }

  private parseGeneratedQuestions(
    raw: string,
    input: QuestionGenerationInput
  ): GeneratedQuestion[] {
    try {
      const parsed = JSON.parse(raw);

      return (parsed.questions || []).map(
        (q: {
          text: string;
          targetDimensions: string[];
          modality: string;
          category: string;
          intimacyLevel: number;
          rationale: string;
        }) => ({
          id: generateId(),
          text: q.text,
          targetDimensions: q.targetDimensions as PersonalityDimension[],
          modality: q.modality as PsychologyModality,
          category: q.category,
          intimacyLevel: Math.min(5, Math.max(1, q.intimacyLevel)) as 1 | 2 | 3 | 4 | 5,
          rationale: q.rationale,
        })
      );
    } catch (error) {
      console.error("Failed to parse generated questions:", error);
      return this.getFallbackQuestions(input.discoveryPhase, input.timeSlot, input.count);
    }
  }

  // ─── Session-Aware Question Generation ──────────────────────────────────

  /**
   * Generate a single session-aware question for the Learn step.
   * Supports MC, open-ended, scale, and ranking formats.
   */
  async generateSessionQuestion(
    profileContext: ProfileContext,
    discoveryDay: number,
    phase: DiscoveryPhase,
    targetDimensions: PersonalityDimension[],
    format: QuestionFormat,
    previousQuestionIds: string[],
    archetypeInsightStyle: string,
    archetypeQuestionTone: string
  ): Promise<SessionQuestion> {
    const aiService = AIModelService.getInstance();

    const systemPrompt = this.buildSessionQuestionSystemPrompt(format, archetypeInsightStyle, archetypeQuestionTone);
    const userPrompt = this.buildSessionQuestionUserPrompt(
      profileContext, discoveryDay, phase, targetDimensions, format, previousQuestionIds
    );

    try {
      const response = await aiService.complete({
        taskType: "question-generation",
        systemPrompt,
        userPrompt,
        temperature: 0.8,
        maxTokens: 1500,
        jsonMode: true,
      });

      return this.parseSessionQuestion(response.content, format);
    } catch (error) {
      console.error("Session question generation failed:", error);
      return this.getFallbackSessionQuestion(phase, format);
    }
  }

  private buildSessionQuestionSystemPrompt(
    format: QuestionFormat,
    insightStyle: string,
    questionTone: string
  ): string {
    const formatInstructions = this.getFormatInstructions(format);

    return `You are a warm, knowledgeable relationship coach crafting a daily question. You speak like a trusted friend who happens to know psychology.

STYLE: ${insightStyle}
TONE: ${questionTone}

This is a SOLO-FIRST app — frame everything as personal growth for better relationships. Not "what does your partner think?" but "what do you notice about yourself?"

${formatInstructions}

RULES:
- Questions should feel like connection exercises, NOT personality tests
- Use warm, conversational language — no clinical terms
- Match intimacy to the discovery day (lower early, higher later)
- Each question should naturally reveal personality signals without feeling like an assessment

Respond with JSON:
{
  "text": "the question text",
  "targetDimensions": ["dimension1"],
  "modality": "PsychologyModality name",
  "intimacyLevel": 1-5,
  ${format === "multiple-choice" ? '"options": [{"id": "a", "text": "option text", "signalHints": [{"dimension": "attachment", "indicator": "secure-base", "strength": 0.7}]}],' : ''}
  ${format === "scale" ? '"scaleLabels": ["Low end label", "High end label"],' : ''}
  ${format === "ranking" ? '"rankingItems": ["item1", "item2", "item3", "item4"],' : ''}
}`;
  }

  private getFormatInstructions(format: QuestionFormat): string {
    switch (format) {
      case "multiple-choice":
        return `Generate a MULTIPLE CHOICE question with 3-4 options. Each option should naturally map to different personality signals. The user picks the one that resonates most. Make options feel like genuine choices, not right/wrong answers. Include signalHints for each option specifying which personality dimension and indicator it reveals.`;
      case "open-ended":
        return `Generate an OPEN-ENDED question that invites a narrative response (2-3 sentences). Frame it as a reflection or memory prompt.`;
      case "scale":
        return `Generate a SCALE question (1-5) with clear, meaningful labels for each end. Include scaleLabels array with [lowLabel, highLabel].`;
      case "ranking":
        return `Generate a RANKING question with 4 items to rank in order of importance. Include rankingItems array.`;
      default:
        return `Generate an open-ended question.`;
    }
  }

  private buildSessionQuestionUserPrompt(
    profileContext: ProfileContext,
    discoveryDay: number,
    phase: DiscoveryPhase,
    targetDimensions: PersonalityDimension[],
    format: QuestionFormat,
    previousQuestionIds: string[]
  ): string {
    return `Generate a ${format} question for ${profileContext.userName}.

Day ${discoveryDay} of 14 | Phase: ${phase} | Comfort: ${Math.round(profileContext.comfortLevel * 100)}%
What we know: ${profileContext.knownTraits}
Dimensions needing signal: ${targetDimensions.slice(0, 3).join(", ")}
${profileContext.sensitivities.length > 0 ? `Be gentle around: ${profileContext.sensitivities.join(", ")}` : ""}
${previousQuestionIds.length > 0 ? `Avoid repeating themes from ${previousQuestionIds.length} previous questions.` : ""}`;
  }

  private parseSessionQuestion(raw: string, expectedFormat: QuestionFormat): SessionQuestion {
    try {
      const parsed = JSON.parse(raw);

      const question: SessionQuestion = {
        id: generateId(),
        text: parsed.text,
        format: expectedFormat,
        targetDimensions: (parsed.targetDimensions || []) as PersonalityDimension[],
        intimacyLevel: Math.min(5, Math.max(1, parsed.intimacyLevel || 2)) as 1 | 2 | 3 | 4 | 5,
        modality: (parsed.modality || "Positive Psychology") as PsychologyModality,
      };

      if (expectedFormat === "multiple-choice" && parsed.options) {
        question.options = parsed.options.map((opt: any, i: number) => ({
          id: opt.id || String.fromCharCode(97 + i), // a, b, c, d
          text: opt.text,
          signalHints: opt.signalHints || [],
        }));
      }

      if (expectedFormat === "scale") {
        question.scaleMin = 1;
        question.scaleMax = 5;
        question.scaleLabels = parsed.scaleLabels || ["Not at all", "Very much"];
      }

      if (expectedFormat === "ranking" && parsed.rankingItems) {
        question.rankingItems = parsed.rankingItems;
      }

      return question;
    } catch (error) {
      console.error("Failed to parse session question:", error);
      return this.getFallbackSessionQuestion("rhythm", expectedFormat);
    }
  }

  private getFallbackSessionQuestion(phase: DiscoveryPhase, format: QuestionFormat): SessionQuestion {
    // Always fall back to open-ended — safer than broken MC
    const fallbacks: Record<DiscoveryPhase, { text: string; dims: PersonalityDimension[]; modality: PsychologyModality; level: 1 | 2 | 3 | 4 | 5 }> = {
      rhythm: { text: "What's one thing that always makes you feel connected to the people you love?", dims: ["values", "emotionalExpression"], modality: "Positive Psychology", level: 1 },
      deepening: { text: "When you've had a difficult day, what does support look like for you?", dims: ["attachment", "loveLanguage"], modality: "Attachment Theory", level: 2 },
      navigating: { text: "Think of a recent disagreement — what would you do differently if you could replay it?", dims: ["conflict", "emotionalExpression"], modality: "Gottman Method", level: 3 },
      layers: { text: "What part of yourself are you most proud of in how you show up in relationships?", dims: ["relationalIdentity", "values"], modality: "Narrative Therapy", level: 3 },
      mirror: { text: "Looking back on these two weeks, what's one thing you've noticed about yourself that surprised you?", dims: ["relationalIdentity", "emotionalExpression"], modality: "Narrative Therapy", level: 3 },
    };

    const fb = fallbacks[phase] || fallbacks.rhythm;

    return {
      id: generateId(),
      text: fb.text,
      format: "open-ended",  // Always fall back to open-ended
      targetDimensions: fb.dims,
      intimacyLevel: fb.level,
      modality: fb.modality,
    };
  }

  // ─── Phase-Specific Dimension Targeting ─────────────────────────────────

  /**
   * Determine which dimensions to prioritize for a given discovery phase.
   * This ensures the right signals are gathered at the right time.
   */
  static getDimensionPriority(
    phase: DiscoveryPhase,
    uncertainDimensions: PersonalityDimension[]
  ): PersonalityDimension[] {
    const phaseTargets: Record<DiscoveryPhase, PersonalityDimension[]> = {
      rhythm: ["values", "emotionalExpression", "relationalIdentity"],
      deepening: ["attachment", "emotionalExpression", "loveLanguage"],
      navigating: ["conflict", "loveLanguage", "attachment"],
      layers: ["intimacy", "emotionalExpression", "values"],
      mirror: ["relationalIdentity", "values", "attachment"],
    };

    const phasePriority = phaseTargets[phase];

    // Prioritize uncertain dimensions that align with the current phase
    const aligned = phasePriority.filter((d) => uncertainDimensions.includes(d));
    const remaining = uncertainDimensions.filter((d) => !aligned.includes(d));

    return [...aligned, ...remaining];
  }

  // ─── Fallback Questions ─────────────────────────────────────────────────

  private getFallbackQuestions(
    phase: DiscoveryPhase,
    timeSlot: "AM" | "PM",
    count: number
  ): GeneratedQuestion[] {
    const fallbacks: Record<DiscoveryPhase, GeneratedQuestion[]> = {
      rhythm: [
        {
          id: generateId(),
          text: "What's one thing that always makes you smile when you think about your relationship?",
          targetDimensions: ["values", "emotionalExpression"],
          modality: "Positive Psychology",
          category: "Appreciation & Gratitude",
          intimacyLevel: 1,
          rationale: "Warm opener — reveals what they value and emotional expressiveness",
        },
        {
          id: generateId(),
          text: "If you could relive one day together from scratch, which would it be and what made it special?",
          targetDimensions: ["values", "loveLanguage"],
          modality: "Narrative Therapy",
          category: "Shared Memories",
          intimacyLevel: 1,
          rationale: "Memory recall reveals values and love language through what they highlight",
        },
        {
          id: generateId(),
          text: "What's something you've been curious to try together but haven't brought up yet?",
          targetDimensions: ["intimacy", "emotionalExpression"],
          modality: "Positive Psychology",
          category: "Adventure & Fun",
          intimacyLevel: 2,
          rationale: "Reveals comfort with new experiences and emotional openness",
        },
      ],
      deepening: [
        {
          id: generateId(),
          text: "When you've had a really difficult day, what does support from your partner look like for you?",
          targetDimensions: ["attachment", "loveLanguage"],
          modality: "Attachment Theory",
          category: "Emotional Intimacy",
          intimacyLevel: 2,
          rationale: "Directly reveals attachment needs and love language preferences",
        },
        {
          id: generateId(),
          text: "What feeling do you find hardest to express to your partner, and what holds you back?",
          targetDimensions: ["emotionalExpression", "attachment"],
          modality: "Emotional Focused Therapy",
          category: "Emotional Intimacy",
          intimacyLevel: 3,
          rationale: "Maps emotional expression boundaries and attachment avoidance",
        },
        {
          id: generateId(),
          text: "Think about a moment when you felt truly understood by your partner. What happened?",
          targetDimensions: ["attachment", "loveLanguage"],
          modality: "Imago Therapy",
          category: "Emotional Intimacy",
          intimacyLevel: 2,
          rationale: "Reveals what 'seen and heard' means to them — attachment and LL signal",
        },
      ],
      navigating: [
        {
          id: generateId(),
          text: "When you and your partner disagree about something that matters, what's your first instinct?",
          targetDimensions: ["conflict", "attachment"],
          modality: "Gottman Method",
          category: "Communication & Conflict",
          intimacyLevel: 3,
          rationale: "Directly maps conflict pattern — pursue, withdraw, or validate",
        },
        {
          id: generateId(),
          text: "What's the kindest thing your partner does for you regularly — something they might not even realize matters?",
          targetDimensions: ["loveLanguage", "values"],
          modality: "Love Languages",
          category: "Love Languages & Affection",
          intimacyLevel: 2,
          rationale: "Confirms love language through what they notice and appreciate",
        },
        {
          id: generateId(),
          text: "After a disagreement, what helps you feel reconnected? What does repair look like between you two?",
          targetDimensions: ["conflict", "attachment"],
          modality: "Gottman Method",
          category: "Communication & Conflict",
          intimacyLevel: 3,
          rationale: "Maps repair capacity and attachment recovery patterns",
        },
      ],
      layers: [
        {
          id: generateId(),
          text: "What part of yourself do you protect most in your relationship — and what would it take to let that guard down?",
          targetDimensions: ["intimacy", "attachment"],
          modality: "Emotional Focused Therapy",
          category: "Emotional Intimacy",
          intimacyLevel: 4,
          rationale: "Maps vulnerability boundaries and attachment avoidance directly",
        },
        {
          id: generateId(),
          text: "How has your definition of intimacy changed since the beginning of your relationship?",
          targetDimensions: ["intimacy", "emotionalExpression"],
          modality: "Attachment Theory",
          category: "Intimacy & Physical",
          intimacyLevel: 3,
          rationale: "Reveals intimacy evolution and comfort with the topic itself",
        },
        {
          id: generateId(),
          text: "What's something your partner does that makes you feel most like yourself?",
          targetDimensions: ["relationalIdentity", "loveLanguage"],
          modality: "Imago Therapy",
          category: "Personal Growth",
          intimacyLevel: 3,
          rationale: "Reveals relational identity — who they are within the partnership",
        },
      ],
      mirror: [
        {
          id: generateId(),
          text: "Over the past two weeks, what's something new you've noticed about yourself or your relationship through these conversations?",
          targetDimensions: ["relationalIdentity", "values"],
          modality: "Narrative Therapy",
          category: "Personal Growth",
          intimacyLevel: 3,
          rationale: "Meta-reflection that reveals self-awareness and growth orientation",
        },
        {
          id: generateId(),
          text: "If your relationship had a superpower — something you do better together than anyone else — what would it be?",
          targetDimensions: ["values", "relationalIdentity"],
          modality: "Positive Psychology",
          category: "Appreciation & Gratitude",
          intimacyLevel: 2,
          rationale: "Celebrates the couple identity and reveals core relational values",
        },
        {
          id: generateId(),
          text: "What's one thing you want your partner to know you've been carrying — something these questions have helped you see more clearly?",
          targetDimensions: ["emotionalExpression", "attachment"],
          modality: "Emotional Focused Therapy",
          category: "Emotional Intimacy",
          intimacyLevel: 4,
          rationale: "Deep vulnerability prompt for the integration phase — capstone moment",
        },
      ],
    };

    const phaseQuestions = fallbacks[phase] || fallbacks.rhythm;

    // Filter by time slot tone preference (AM = lighter, PM = deeper)
    if (timeSlot === "AM") {
      phaseQuestions.sort((a, b) => a.intimacyLevel - b.intimacyLevel);
    } else {
      phaseQuestions.sort((a, b) => b.intimacyLevel - a.intimacyLevel);
    }

    return phaseQuestions.slice(0, count);
  }
}
