-- Growth Ecosystem: new tables + extended columns
-- Adds: growth_thread, weekly_mirrors tables
-- Extends: daily_sessions, user_insights, user_journeys

-- ─── NEW TABLE: growth_thread ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS growth_thread (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  label TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('milestone', 'breakthrough', 'pattern', 'mirror', 'pinned')),
  journey_id TEXT,
  detail TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE growth_thread ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users access own growth_thread"
  ON growth_thread FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_growth_thread_user_id
  ON growth_thread (user_id, date DESC);

-- ─── NEW TABLE: weekly_mirrors ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS weekly_mirrors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  narrative_text TEXT NOT NULL,
  practice_count INTEGER DEFAULT 0,
  practices_felt_natural INTEGER DEFAULT 0,
  key_patterns JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (user_id, week_start)
);

ALTER TABLE weekly_mirrors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users access own weekly_mirrors"
  ON weekly_mirrors FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_weekly_mirrors_user_id
  ON weekly_mirrors (user_id, week_start DESC);

-- ─── EXTEND: daily_sessions ────────────────────────────────────────────────────
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'daily_sessions' AND column_name = 'practice_attempted'
  ) THEN
    ALTER TABLE daily_sessions ADD COLUMN practice_attempted BOOLEAN;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'daily_sessions' AND column_name = 'evening_emotional_tone'
  ) THEN
    ALTER TABLE daily_sessions ADD COLUMN evening_emotional_tone TEXT;
  END IF;
END $$;

COMMENT ON COLUMN daily_sessions.practice_attempted IS 'Whether the user attempted the micro-action (set during evening check-in). NULL = not yet checked in.';
COMMENT ON COLUMN daily_sessions.evening_emotional_tone IS 'AI-detected emotional tone from evening check-in (e.g. hopeful, frustrated, calm).';

-- ─── EXTEND: user_insights ─────────────────────────────────────────────────────
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'user_insights' AND column_name = 'next_greeting_text'
  ) THEN
    ALTER TABLE user_insights ADD COLUMN next_greeting_text TEXT;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'user_insights' AND column_name = 'journey_completion_state'
  ) THEN
    ALTER TABLE user_insights ADD COLUMN journey_completion_state TEXT
      CHECK (journey_completion_state IN ('pending_decision', 'resting'));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'user_insights' AND column_name = 'recommended_next_journeys'
  ) THEN
    ALTER TABLE user_insights ADD COLUMN recommended_next_journeys JSONB;
  END IF;
END $$;

COMMENT ON COLUMN user_insights.next_greeting_text IS 'Pre-generated Peter greeting for next dashboard visit. Fire-and-forget at session end.';
COMMENT ON COLUMN user_insights.journey_completion_state IS 'Post-journey state: pending_decision (awaiting choice) or resting (rest day). NULL = in journey or pre-journey.';
COMMENT ON COLUMN user_insights.recommended_next_journeys IS 'Array of recommended journey IDs after completion. Generated by next-journey-recommender.';

-- ─── EXTEND: user_journeys ─────────────────────────────────────────────────────
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'user_journeys' AND column_name = 'completion_synthesis'
  ) THEN
    ALTER TABLE user_journeys ADD COLUMN completion_synthesis TEXT;
  END IF;
END $$;

COMMENT ON COLUMN user_journeys.completion_synthesis IS 'Peter journey synthesis: what shifted from Day 1 to completion.';
