// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbljcvqiiurfbjquhbxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ibGpjdnFpaXVyZmJqcXVoYnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MzUzMzAsImV4cCI6MjA1NjAxMTMzMH0.pDb4vjIdSTvRPGHAtolC47Icu2o3DXKhlwVllv6GvOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export const clearCache = async () => {
  await supabase.auth.signOut()
  // Additional steps to clear cache if needed
}